### PR TITLE
Use yellow background and underline for project find results

### PR DESCRIPTION
**Pull request by jtbandes**
This style is a de facto standard across a handful of popular Mac apps.

screen shot 2016-09-10 at 12 50 09 am

### CODE REVIEW

**Comment by sorbits** [comment]
Merged as e0a49637f98df8b5b272037441ad4cc4d2d5b3b0, thanks!

How did you settle on these exact colors?

**Comment by jtbandes** [comment]
I inspected some popular implementations of this style, used a color meter, and did a few calculations 😉

**Comment by jtbandes** [comment]
(of course, there is no absolute standard to uphold — change them to your liking!)

**Comment by rdwampler** [comment]
Should this style be applied to `OakChooser`'s "search" results too? (Xcode seems to apply this everywhere for all "search" results)

**Comment by jtbandes** [comment]
@rdwampler That's a good point, it probably should be.

**Pull request closed without merging**
