### PR TITLE
TouchBar Support

### PR DESCRIPTION
**Pull request by jakecast**
I added basic touchbar support in the DocumentWindowController. Currently it just has next/previous tab buttons and a quickly open button for navigating tabs and projects. I might add more shortcuts down the line. Not a lot of customization here (sorry), just adding it for my own use at the moment.
It also has keyboard autocomplete support for the text input in the standard fields (Find Window, Save WIndow, Dialogs, etc.).
@sorbits let me know if this one works okay for merging in. the assets are from the standard touchbar library or included macOS touchbar assets.

### CODE REVIEW

**Comment by jakecast** [comment]
touch bar shot 2017-06-19 at 15 54 15

Screenshot of current support. From left to right.
Previous Tab - Next Tab -- New Tab -- Open Quickly ---- Open Recent Projects/Favorites

**Comment by koenpunt** [comment]
This is nice start, but all the options you added are all available without using any of the function keys. I would find it far more useful if options now available as function keys would show up in the touchbar. For example working bookmarks (create bookmark <kbd>CMD</kbd> <kbd>F2</kbd>/ next bookmark <kbd>F2</kbd>).

**Comment by sorbits** [comment]
Please follow the style of the existing code base and do *not* make style changes to existing code!

**Comment by jakecast** [comment]
@koenpunt yeah, ideally there would be a way to customize the touchbar set for each user's needs and preferences. i was just trying to get baseline support in there for now and picked the options i used most often. down the line i'd add more customization, but getting in the basic stuff was what i was looking at now and making sure the document window controller can be treated as a NSWindowController safely was my biggest concern

@sorbits sorry about that, i had some auto-formatting on as i was browsing through files. I'll walk through and undo the superfluous changes

**Comment by koenpunt** [comment]
@jakecast I mean that because the touchbar hides the function keys,  the first options I'd like to see (and I can imagine others with me) are the ones that require the F keys.

**Comment by jakecast** [comment]
@sorbits I removed the extraneous style changes & formatting. sorry again about that. was a quick oversight of highlighting text and saving files without realizing it was applying formatting on objc!

**Comment by sorbits** [comment]
> @sorbits I removed the extraneous style changes & formatting […]

Thanks, however, please rebase this so there is only one commit per feature you have added, right now there are ten commits, some undoing previous commits.

**Pull request closed without merging**
