### PR TITLE
All tabstop modified files

### PR DESCRIPTION
**Pull request by bj7**
Committing all tabstop modified files after branch cleanup. Sorry for any confusion. I had to reset hard my branch because it was so messy with the changes. I combined all changes into one commit for this. Please let me know if I should do anything else. Thanks again.

### CODE REVIEW

**Comment by bj7** [comment]
Out of curiosity, do you have a TODO sheet anywhere? I was wondering what else needed immediate attention. I'm trying to work the the Mini-Map plugin into the core currently.

**Comment by sorbits** [comment]
Merged as 263da53c8166273859c91c1a88ef2157d1d05ca8, thanks!

I made a few changes:

1. Code style: Your code style was basically as different as it could be from mine (indent with spaces, Egyptian braces, different spacing rules for parenthesis, etc.)
2. I pluralized the “Indent Guide” → “Indent Guides”.
3. `OakTextView.mm` had some code to add a `showIndentGuide` instance variable with a setter, but otherwise seemed unused, so I removed this.

**Comment by sorbits** [comment]
> Out of curiosity, do you have a TODO sheet anywhere? I was wondering what else needed immediate attention

Sorry, I don’t keep a public todo. What needs immediate attention probably depends on who you ask :)

Btw: for the indent guides, many will probably expect them to only be drawn on lines containing leading tabs/spaces, but that is of course much more involved.

**Comment by bj7** [comment]
I'm sorry about the code style; I'll keep that better controlled next time. 

> Btw: for the indent guides, many will probably expect them to only be drawn on lines containing leading tabs/spaces, but that is of course much more involved.

I am aware of that. I want to have all tab stops only showing at indentation levels, but you're right. That's much more in depth. I have plans to update to that, but I had thought a good first step would be mimicking the BBEdit style since it is simpler.

**Comment by jacob-carlborg** [comment]
> Out of curiosity, do you have a TODO sheet anywhere? I was wondering what else needed immediate attention

Not sure if it counts as "immediate attention" (😃) but I would love to see [inline marks](https://github.com/textmate/textmate/pull/1297) and [split views](https://github.com/sclukey/textmate/commits/split_views). Unfortunately currently I don't have time to work on the inline marks feature.

Another thing I would like to see support for is strikethrough text. I'm thinking that can be used to highlight things that are deprecated.

> I'm trying to work the the Mini-Map plugin into the core currently.

Awesome. Looking forward to see that.

**Comment by sorbits** [comment]
> Out of curiosity, do you have a TODO sheet anywhere?

I updated https://github.com/textmate/textmate/wiki/Hacking-on-the-Code

It is not a to-do per se, it’s more of an “issues with low barrier to entry that I am not that likely to work on myself in the nearest future”.

/cc @jtbandes

**Pull request closed without merging**
