### PR TITLE
SyntaxMate: XPC Service for third-party apps

### PR DESCRIPTION
**Pull request by shpakovski**
Hello!

This XPC Service can be copied into any Mac app and then used like `sourcekit` in Xcode.
I was not sure if it makes sense to bloat this folder with one more app.
So you would find the [Demo](https://github.com/shpakovski/SyntaxMateDemo) project in my personal repo.

Any feedback? 😃

### CODE REVIEW

**Comment by sorbits** [comment]
I would prefer not to add all the grammars and themes to this repository. I suggest either a submodule or (better) a script to fetch all these items.

**Comment by shpakovski** [comment]
> I would prefer not to add all the grammars and themes to this repository.

I kind of needed confirmation. Thanks! 😃 A separate repo with `.tmLanguage` and `.tmTheme` files is a way to go. Please stay tuned…

**Comment by shpakovski** [comment]
Alright, done! The rewritten commit is not that huge and contains only code. Please verify?

**Comment by sorbits** [comment]
Thanks for the update, and sorry for my slow response times.

Would you mind changing the coding style to follow the rest of the TextMate project?

The things I noticed are:

- [ ] No space before `*`, e.g. `NSString*` and not `NSString *`.
- [ ] Indent done with tabs and tab size = 3 (the PR has a mix of tabs and spaces).
- [ ] Brace on its own line
- [ ] No braces for single line bodies
- [ ] No space after control keywords (`if`, `for`, `while`, etc.)
- [ ] Do not use `__auto_type`. You _can_ use `auto` (Objective-C++), but for simple types, I prefer to have the type there.

Examples of TextMate style:

	if(reply == nil)
		return;

and

	if(reply == nil)
	{
		do_something();
		and_something_else();
	}

**Comment by shpakovski** [comment]
Thanks Allan, I will!

**Comment by rdwampler** [comment]
Would it be possible for TextMate itself to run this XPC service and allow bundles to communicate with it? 

I assume one could write a ruby library using the c api on the bundle side. The potential use I would like to see is for a bundle command to pass some text to the XPC service and have it return html containing CSS classes of the appropriate scopes, which then could be displayed in a web view (command output). I.e., provide syntax highlighting for some of git bundle commands (e.g., diff and blame).

I have the latter (html) part working with a modified version of `gtm`. But maybe it might be more appropriate here?

Just a thought.

**Comment by shpakovski** [comment]
Should be good now, could you please verify? Thanks!

**Comment by sorbits** [comment]
Merged as 2156555057af53065248d1bc9e93ab35eb7bfa6f, sorry for taking so long with this one, my head has been elsewhere for the last many months…

I would appreciate if you could add `Applications/SyntaxMate/README.md` to give people basic understanding of how to use and when to use, etc.

**Comment by shpakovski** [comment]
> Merged, sorry for taking so long with this one, my head has been elsewhere for the last many months…

Hi Alan, no problem! Thanks a lot and good luck with launching 2.0 💪

> I would appreciate if you could add Applications/SyntaxMate/README.md to give people basic understanding of how to use and when to use, etc.

I will, please stay tuned 👌

**Pull request closed without merging**
