### PR TITLE
Basic TouchBar Support

### PR DESCRIPTION
**Pull request by jakecast**
I added basic touchbar support in the DocumentWindowController. Currently it just has next/previous tab buttons and a quickly open button for navigating tabs and projects. I might add more shortcuts down the line. Not a lot of customization here (sorry), just adding it for my own use at the moment.
It also has keyboard autocomplete support for the text input in the standard fields (Find Window, Save WIndow, Dialogs, etc.).

touch bar shot 2017-06-20 at 00 42 04

Screenshot of current support. From left to right.
Previous Tab - Next Tab -- New Tab -- Open Quickly ---- Find in Project -- Open Recent Projects/Favorites

@sorbits I went ahead and merged the changes into a single commit, let me know if this works okay..

### CODE REVIEW

**Comment by sorbits** [comment]
I suggest renaming the images to have a `Template` prefix and then get rid of the `NSImage` extension.

**Comment by jakecast** [comment]
@sorbits I have updated the image naming to include the `Template` keyword and removed the added `NSImage` extension as well as its import from the DocumentWindowController

**Comment by jakecast** [comment]
@sorbits anything else I can do to help incorporate these changes?

**Comment by sorbits** [comment]
Sorry for being a bit slow to react on this, I am currently working on 
another project which gets all my mental capacity.

I think I will get to this in the next week or so.

Though now that you ask, it would be a help if you format your code like 
the rest of the TextMate code base, because I will have to otherwise do 
this for you before I can even review the code.

Please also squash commits — I want one commit per feature to review, 
I do not want to pull a commit which has changes undone in a later 
commit.

And you can just force push updated commits to your PR branch instead of 
closing and re-opening pull requests.

**Comment by jakecast** [comment]
@sorbits 
mmk, I have rebased this pull request based on the current master branch and squashed all my changes into a single commit.
I also tried to follow the convention I saw within the rest of the TM codebase with the added code, but if I missed anything that jumps out at you let me know and I can update it.

**Comment by sorbits** [comment]
Merged as f96ffb63bac40a0af34b5dc56ce363b9b97effd1, thanks!

I noticed you changed the superclass of the `DocumentWindowController` to `NSWindowController`. I assume this was required for AppKit to call `makeTouchBar`, but as a window controller superclass may come with some hidden changes, I made it a `NSResponder` for now — though long-term the proper superclass is `NSWindowController`, the reason it was `NSObject` is (iirc) because there was a problem with weak references to `NSWindowController` instances.

I removed a few helper methods, as these weren’t strictly needed.

I am curious why the images are both in 1x and 2x, is that just for the simulator? As I assume the touch bar hardware itself only use the 2x images.

**Pull request closed without merging**
